### ISSUE TITLE
Missing assets

### ISSUE THREAD

**Issue by fdalvi** [qcri/LLMeBench#201]
The following assets exist but are not committed yet:

- [x] factuality/COVID19Factuality_GPT35_ZeroShot #216
- [x] factuality/UnifiedFCFactuality_GPT35_ZeroShot #215
- [x] hate_speech/OSACT4SubtaskB_GPT4_ZeroShot #224 
- [x] hate_speech/OSACT4SubtaskB_BLOOMZ_ZeroShot #218
- [x] sarcasm/ArSarcasm2_BLOOMZ_ZeroShot #187 
- [x] sentiment/ArSAS_GPT4_FewShot #217
- [x] diacritization/BibleMaghrebi_GPT4_FewShot #223
- [x] diacritization/WikiNews_GPT4_FewShot #223
- [x] parsing/PADT_GPT4_FewShot #221
- [x] segmentation/QCRIDialectalArabic_GPT4_FewShot #222 
- [x] segmentation/WikiNews_GPT4_FewShot #222 

all under `ar`

**Comment by fdalvi** [comment]
All done
